# Generated by Django 4.0.4 on 2022-04-13 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotescrud', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='text',
        ),
    ]
